spring.application.name=API_EspecieExtionsion
spring.profiles.active=prod
app.version=1.0.0
# JWT
jwt.secret=yoNoDuermoSinMiBaigonPorQueSiNoDuermoSoyEsquizofrenicoYmeDaMIEDO
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Permite Swagger sin auth (si usas springdoc)
springdoc.api-docs.enabled=true
